# -*- coding: utf-8 -*-
"""MiniProject_Colab_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QbioPmKMI-f9PiAoxhQ2iHl51yBK_sJw
"""

from google.colab import drive

drive.mount("/content/drive")

import os

# Set working directory to your specific folder path
PROJECT_PATH = "/content/drive/MyDrive/A4StarterCode (1)/A4StarterCode"
os.chdir(PROJECT_PATH)

print("Current Working Directory:", os.getcwd())
print("\nFiles in folder:")
!ls -la

import glob
from pathlib import Path

# Search for the ultrasound volume recursively
mha_files = list(Path(".").rglob("*ultrasound.mha"))

if mha_files:
    DATA_DIR = str(mha_files[0].parent)
    print(f"[+] Found dataset directory at: '{DATA_DIR}'")
else:
    print(
        "[-] Could not find .mha files! Please check your Google Drive folder."
    )

dataset_patch = """import os
import torch
from torch.utils.data import Dataset, DataLoader
from pathlib import Path
import SimpleITK as sitk
import numpy as np

class MicroSegDataset(Dataset):
    def __init__(self, data_dir, split="train", transform=None):
        self.data_dir = data_dir
        self.split = split
        self.transform = transform

        data_path = Path(data_dir)
        img_paths = sorted([str(p) for p in data_path.rglob("*ultrasound.mha")])
        seg_paths = sorted([str(p) for p in data_path.rglob("*segment.mha")])

        if not img_paths or not seg_paths:
            raise FileNotFoundError(f"Could not find .mha volume files in {data_dir}")

        # Load SimpleITK volumes into numpy arrays
        us_img = sitk.GetArrayFromImage(sitk.ReadImage(img_paths[0]))
        seg_img = sitk.GetArrayFromImage(sitk.ReadImage(seg_paths[0]))

        # Split 80% train / 20% val
        num_slices = us_img.shape[0]
        split_idx = int(num_slices * 0.8)

        if split == "train":
            self.images = us_img[:split_idx]
            self.masks = seg_img[:split_idx]
        else:
            self.images = us_img[split_idx:]
            self.masks = seg_img[split_idx:]

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        img = self.images[idx]
        mask = self.masks[idx]

        # Add channel dimension (1, H, W) and normalize to [0, 1]
        img = torch.tensor(img, dtype=torch.float32).unsqueeze(0)
        mask = torch.tensor(mask, dtype=torch.float32).unsqueeze(0)

        if img.max() > 1.0:
            img = img / 255.0
        mask = (mask > 0).float()

        return img, mask

def MicroSegLoader(dataset, batch_size=8, shuffle=True):
    return DataLoader(dataset, batch_size=batch_size, shuffle=shuffle)
"""

with open("src/utils/dataset.py", "w") as f:
    f.write(dataset_patch)

print("[+] Updated src/utils/dataset.py with robust Path parsing!")

!pip install simpleitk monai

dataset_patch = """import os
import torch
from torch.utils.data import Dataset, DataLoader
from pathlib import Path
import SimpleITK as sitk
import numpy as np

class MicroSegDataset(Dataset):
    def __init__(self, data_dir, split="train", val_ratio=0.2):
        self.data_dir = data_dir
        self.split = split

        data_path = Path(data_dir)
        img_paths = sorted([str(p) for p in data_path.rglob("*ultrasound.mha")])
        seg_paths = sorted([str(p) for p in data_path.rglob("*segment.mha")])

        if not img_paths or not seg_paths:
            raise FileNotFoundError(f"Could not find .mha volume files in {data_dir}")

        # Load volumes via SimpleITK
        us_arr = sitk.GetArrayFromImage(sitk.ReadImage(img_paths[0]))
        seg_arr = sitk.GetArrayFromImage(sitk.ReadImage(seg_paths[0]))

        # Remove single-depth dimension -> Shape becomes (10048, 512)
        us_arr = np.squeeze(us_arr)
        seg_arr = np.squeeze(seg_arr)

        height, width = us_arr.shape[0], us_arr.shape[1]

        # Calculate maximum full square slices (512x512)
        slice_dim = width  # 512
        num_slices = height // slice_dim  # 10048 // 512 = 19 full slices

        crop_height = num_slices * slice_dim  # 9728

        # Reshape into (Num_Slices, 512, 512)
        us_vol = us_arr[:crop_height, :].reshape(num_slices, slice_dim, slice_dim)
        seg_vol = seg_arr[:crop_height, :].reshape(num_slices, slice_dim, slice_dim)

        val_size = max(1, int(num_slices * val_ratio))
        train_size = num_slices - val_size

        if split == "train":
            self.images = us_vol[:train_size]
            self.masks = seg_vol[:train_size]
        else:
            self.images = us_vol[train_size:]
            self.masks = seg_vol[train_size:]

        print(f"[Dataset] Split '{split}' loaded with {len(self.images)} slices of shape ({slice_dim}, {slice_dim}).")

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        img = self.images[idx]
        mask = self.masks[idx]

        # Convert to PyTorch float tensors with channel dim (1, 512, 512)
        img_tensor = torch.tensor(img, dtype=torch.float32).unsqueeze(0)
        mask_tensor = torch.tensor(mask, dtype=torch.float32).unsqueeze(0)

        # Normalize intensity
        if img_tensor.max() > 1.0:
            img_tensor = img_tensor / 255.0
        mask_tensor = (mask_tensor > 0).float()

        return img_tensor, mask_tensor

def MicroSegLoader(dataset, batch_size=8, shuffle=True):
    actual_batch_size = max(1, min(batch_size, len(dataset)))
    return DataLoader(
        dataset,
        batch_size=actual_batch_size,
        shuffle=shuffle if len(dataset) > 0 else False
    )
"""

with open("src/utils/dataset.py", "w") as f:
    f.write(dataset_patch)

print("[+] Successfully updated src/utils/dataset.py!")

from pathlib import Path
import SimpleITK as sitk

mha_files = list(Path(".").rglob("*ultrasound.mha"))
if mha_files:
    img_path = str(mha_files[0])
    image = sitk.ReadImage(img_path)
    arr = sitk.GetArrayFromImage(image)

    print("=== SimpleITK Metadata ===")
    print("Image Size (X,Y,Z):", image.GetSize())
    print("Image Dimension:", image.GetDimension())
    print("Image Pixel ID:", image.GetPixelIDTypeAsString())
    print("Numpy Array Shape:", arr.shape)
    print("Numpy Array Size:", arr.size)

metrics_code = """import torch
import numpy as np
from scipy.spatial.distance import directed_hausdorff

def logits_to_binary_mask(logits, threshold=0.5):
    out_channels = logits.shape[1]
    if out_channels == 1:
        probs = torch.sigmoid(logits)
        return (probs > threshold).float()
    elif out_channels == 2:
        pred_class = torch.argmax(torch.softmax(logits, dim=1), dim=1, keepdim=True)
        return pred_class.float()
    else:
        raise ValueError(f"Unexpected out_channels: {out_channels}")


def dice_score(pred_mask, target_mask, eps=1e-6):
    pred_flat = pred_mask.view(pred_mask.size(0), -1)
    target_flat = target_mask.view(target_mask.size(0), -1)

    intersection = (pred_flat * target_flat).sum(dim=1)
    denominator = pred_flat.sum(dim=1) + target_flat.sum(dim=1)

    dice_per_image = (2.0 * intersection + eps) / (denominator + eps)
    return dice_per_image.mean()


def iou_score(pred_mask, target_mask, eps=1e-6):
    pred_flat = pred_mask.view(pred_mask.size(0), -1)
    target_flat = target_mask.view(target_mask.size(0), -1)

    intersection = (pred_flat * target_flat).sum(dim=1)
    union = pred_flat.sum(dim=1) + target_flat.sum(dim=1) - intersection

    iou_per_image = (intersection + eps) / (union + eps)
    return iou_per_image.mean()


def hausdorff_distance(pred_mask, target_mask):
    \"\"\"
    Memory-efficient Hausdorff distance calculation using SciPy on CPU.
    \"\"\"
    batch_size = pred_mask.size(0)
    hausdorff_per_image = []

    # Move tensors to CPU and convert to numpy for memory-safe distance computation
    pred_np = pred_mask.squeeze(1).detach().cpu().numpy()
    target_np = target_mask.squeeze(1).detach().cpu().numpy()

    for b in range(batch_size):
        pred_coords = np.argwhere(pred_np[b] > 0)
        target_coords = np.argwhere(target_np[b] > 0)

        if len(pred_coords) == 0 and len(target_coords) == 0:
            hausdorff_per_image.append(0.0)
            continue
        elif len(pred_coords) == 0 or len(target_coords) == 0:
            h, w = pred_mask.shape[2:]
            max_dist = (h**2 + w**2) ** 0.5
            hausdorff_per_image.append(max_dist)
            continue

        # Subsample coordinates if point cloud is extremely large (>2000 points)
        if len(pred_coords) > 2000:
            idx = np.random.choice(len(pred_coords), 2000, replace=False)
            pred_coords = pred_coords[idx]
        if len(target_coords) > 2000:
            idx = np.random.choice(len(target_coords), 2000, replace=False)
            target_coords = target_coords[idx]

        d_pred_target = directed_hausdorff(pred_coords, target_coords)[0]
        d_target_pred = directed_hausdorff(target_coords, pred_coords)[0]

        hd = max(d_pred_target, d_target_pred)
        hausdorff_per_image.append(hd)

    return torch.tensor(np.mean(hausdorff_per_image), device=pred_mask.device)


def batch_segmentation_metrics(logits, target_mask, threshold=0.5):
    pred_mask = logits_to_binary_mask(logits, threshold=threshold)

    return {
        "dice": dice_score(pred_mask, target_mask).item(),
        "iou": iou_score(pred_mask, target_mask).item(),
        "hausdorff": hausdorff_distance(pred_mask, target_mask).item(),
    }
"""

with open("src/utils/metrics.py", "w") as f:
    f.write(metrics_code)

print("[+] Successfully updated src/utils/metrics.py with memory-safe Hausdorff distance!")

!python train.py --model_architecture unet --data_dir "$DATA_DIR" --epochs 25 --batch_size 8 --learning_rate 1e-3 --ckpt_dir ./checkpoints/unet

!python train.py --model_architecture attention_unet --data_dir "$DATA_DIR" --epochs 25 --batch_size 8 --learning_rate 1e-3 --ckpt_dir ./checkpoints/attention_unet

!python train.py --model_architecture segresnet --data_dir "$DATA_DIR" --epochs 25 --batch_size 8 --learning_rate 1e-3 --ckpt_dir ./checkpoints/segresnet

eval_code = '''import os
import argparse
import torch
import matplotlib.pyplot as plt

from src.models import build_model
from src.utils.dataset import MicroSegDataset, MicroSegLoader
from src.utils.metrics import batch_segmentation_metrics, logits_to_binary_mask


def parse_args():
    parser = argparse.ArgumentParser(description="Evaluate segmentation models on MicroSeg")
    parser.add_argument("--model_architecture", type=str, default="unet", help="Architecture name")
    parser.add_argument("--ckpt_path", type=str, required=True, help="Path to checkpoint .pth file")
    parser.add_argument("--data_dir", type=str, required=True, help="Directory containing data")
    parser.add_argument("--output_dir", type=str, default="./results", help="Directory to save qualitative overlays")
    return parser.parse_args()


def evaluate(args):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    os.makedirs(args.output_dir, exist_ok=True)

    # 1. Load Dataset (using 'val' or 'test' split)
    try:
        test_dataset = MicroSegDataset(args.data_dir, split="test")
    except Exception:
        print("[!] 'test' split not found, falling back to 'val' split for evaluation.")
        test_dataset = MicroSegDataset(args.data_dir, split="val")

    test_loader = MicroSegLoader(test_dataset, batch_size=1, shuffle=False)

    # 2. Load Model & Weights
    model = build_model(args.model_architecture).to(device)
    checkpoint = torch.load(args.ckpt_path, map_location=device)

    # Handle checkpoints saved as dict or direct state_dict
    if isinstance(checkpoint, dict) and "model_state_dict" in checkpoint:
        model.load_state_dict(checkpoint["model_state_dict"])
    else:
        model.load_state_dict(checkpoint)

    model.eval()
    print(f"[+] Loaded weights successfully from: {args.ckpt_path}")

    # 3. Quantitative Metric Accumulation
    dice_list, iou_list, hd_list = [], [], []

    with torch.no_grad():
        for i, (images, masks) in enumerate(test_loader):
            images, masks = images.to(device), masks.to(device)
            outputs = model(images)

            metrics = batch_segmentation_metrics(outputs, masks)
            dice_list.append(metrics["dice"])
            iou_list.append(metrics["iou"])
            hd_list.append(metrics["hausdorff"])

            # 4. Save Qualitative Overlays for the first 3 images
            if i < 3:
                pred_mask = logits_to_binary_mask(outputs).cpu().squeeze().numpy()
                img_np = images.cpu().squeeze().numpy()
                gt_mask = masks.cpu().squeeze().numpy()

                fig, axes = plt.subplots(1, 3, figsize=(12, 4))
                axes[0].imshow(img_np, cmap="gray")
                axes[0].set_title("Ultrasound Image")
                axes[0].axis("off")

                axes[1].imshow(img_np, cmap="gray")
                axes[1].imshow(gt_mask, cmap="jet", alpha=0.5)
                axes[1].set_title("Ground Truth Mask")
                axes[1].axis("off")

                axes[2].imshow(img_np, cmap="gray")
                axes[2].imshow(pred_mask, cmap="jet", alpha=0.5)
                axes[2].set_title("Predicted Mask")
                axes[2].axis("off")

                save_path = os.path.join(args.output_dir, f"{args.model_architecture}_overlay_sample_{i+1}.png")
                plt.tight_layout()
                plt.savefig(save_path)
                plt.close()
                print(f"[+] Saved qualitative figure to: {save_path}")

    # Summary Results
    mean_dice = sum(dice_list) / len(dice_list)
    mean_iou = sum(iou_list) / len(iou_list)
    mean_hd = sum(hd_list) / len(hd_list)

    print()
    print("="*40)
    print(f"EVALUATION RESULTS ({args.model_architecture.upper()})")
    print("="*40)
    print(f"Mean Dice Score:         {mean_dice:.4f}")
    print(f"Mean IoU Score:          {mean_iou:.4f}")
    print(f"Mean Hausdorff Distance: {mean_hd:.4f}")
    print("="*40)
    print()


if __name__ == "__main__":
    args = parse_args()
    evaluate(args)
'''

with open("eval.py", "w") as f:
    f.write(eval_code)

print("[+] Successfully re-wrote eval.py without syntax errors!")

import os

print("=== Searching /content for any .pth or .pt files ===")
for root, dirs, files in os.walk("/content"):
    for file in files:
        if file.endswith((".pth", ".pt", ".tar", ".ckpt")):
            print(os.path.join(root, file))

!python eval.py --model_architecture unet --ckpt_path "/content/drive/MyDrive/A4StarterCode (1)/A4StarterCode/checkpoints/unet/best_unet.pt" --data_dir "{DATA_DIR}"

!python eval.py --model_architecture attention_unet --ckpt_path "/content/drive/MyDrive/A4StarterCode (1)/A4StarterCode/checkpoints/attention_unet/best_attention_unet.pt" --data_dir "{DATA_DIR}"

!python eval.py --model_architecture segresnet --ckpt_path "/content/drive/MyDrive/A4StarterCode (1)/A4StarterCode/checkpoints/segresnet/best_segresnet.pt" --data_dir "{DATA_DIR}"

